// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4wWu0ZCAnTEaVzlR7ZYuaEYk3j1QIZ0',
    appId: '1:560853758094:web:670c9dcca282d8a08c19df',
    messagingSenderId: '560853758094',
    projectId: 'bookfet-e9521',
    authDomain: 'bookfet-e9521.firebaseapp.com',
    storageBucket: 'bookfet-e9521.appspot.com',
    measurementId: 'G-12EY5EJPWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ytgxpeI_pjPSOJEDsodIgQNnYhISt4Q',
    appId: '1:560853758094:android:56990f35ae82bf028c19df',
    messagingSenderId: '560853758094',
    projectId: 'bookfet-e9521',
    storageBucket: 'bookfet-e9521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYKN5xhh0VTfzrdMghsjIWj_97xpntVQ',
    appId: '1:560853758094:ios:96b6b2c379db8b2c8c19df',
    messagingSenderId: '560853758094',
    projectId: 'bookfet-e9521',
    storageBucket: 'bookfet-e9521.appspot.com',
    androidClientId: '560853758094-nam1vknmtf72bv19ah4qb5to8qoj53t3.apps.googleusercontent.com',
    iosClientId: '560853758094-vfciqbfqnhav5vlf5lb7ln5r4t4jfbhg.apps.googleusercontent.com',
    iosBundleId: 'com.bookfet.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrYKN5xhh0VTfzrdMghsjIWj_97xpntVQ',
    appId: '1:560853758094:ios:837c525f4444865f8c19df',
    messagingSenderId: '560853758094',
    projectId: 'bookfet-e9521',
    storageBucket: 'bookfet-e9521.appspot.com',
    androidClientId: '560853758094-nam1vknmtf72bv19ah4qb5to8qoj53t3.apps.googleusercontent.com',
    iosClientId: '560853758094-fuc2mmiefdpbk7l86juhpaedlgritdob.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloctest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm4wWu0ZCAnTEaVzlR7ZYuaEYk3j1QIZ0',
    appId: '1:560853758094:web:f4129f414161d6d28c19df',
    messagingSenderId: '560853758094',
    projectId: 'bookfet-e9521',
    authDomain: 'bookfet-e9521.firebaseapp.com',
    storageBucket: 'bookfet-e9521.appspot.com',
    measurementId: 'G-56KDS7S7WQ',
  );

}